import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { AlertTriangle } from 'lucide-react';

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-4 md:p-8">
      <div className="max-w-4xl mx-auto space-y-6">
        <h1 className="text-3xl font-bold text-white flex items-center gap-3">
          <AlertTriangle className="w-8 h-8 text-amber-500" />
          Disclaimer
        </h1>
        
        <Card className="border-0 bg-slate-800/50 border border-slate-700">
          <CardHeader>
            <CardTitle className="text-white">Terms of Use</CardTitle>
          </CardHeader>
          <CardContent className="text-slate-300 space-y-4">
            <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>
            
            <h3 className="text-white font-semibold mt-6">AI-Generated Content</h3>
            <p>All content generated by our AI tools is provided for informational purposes. While we strive for accuracy, users should verify all information and consult with professionals before making business decisions.</p>
            
            <h3 className="text-white font-semibold mt-6">No Guarantee of Results</h3>
            <p>BrandForge provides tools and resources to help build businesses, but we do not guarantee specific outcomes, revenue, or success. Business results depend on many factors beyond our platform.</p>
            
            <h3 className="text-white font-semibold mt-6">Professional Advice</h3>
            <p>Our AI-generated business plans and financial projections are not a substitute for professional legal, financial, or business consulting. Always consult qualified professionals for critical business decisions.</p>
            
            <h3 className="text-white font-semibold mt-6">Limitation of Liability</h3>
            <p>BrandForge and its affiliates are not liable for any business decisions, financial losses, or outcomes resulting from use of our platform or AI-generated content.</p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}