import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { AlertCircle, RefreshCw, Loader2 } from 'lucide-react';
import { motion } from 'framer-motion';
import { useDocumentManagement } from '@/hooks/useDocumentManagement';

import EngagementInfoForm from '@/components/TermsOfEngagement/EngagementInfoForm';
import DocumentContent from '@/components/documents/DocumentContent';
import DocumentVersionHistory from '@/components/documents/DocumentVersionHistory';

export default function TermsOfEngagement() {
  const [engagementInfo, setEngagementInfo] = useState({
    clientName: '',
    engagementType: 'consulting',
    scope: '',
    fees: '',
    date: new Date().toISOString().split('T')[0]
  });
  const [terms, setTerms] = useState(null);
  const { isGenerating, lastSaved, versions, restoreVersion } = useDocumentManagement('TermsOfEngagement');

  const generateTerms = async () => {
    if (!engagementInfo.clientName) {
      alert('Please enter client name first');
      return;
    }

    const result = await base44.functions.invoke('generateTermsOfEngagement', {
      engagementInfo,
      platformName: 'Business Annex'
    });

    setTerms(result.terms || result);
  };

  const exportPDF = async () => {
    try {
      await base44.functions.invoke('exportTermsOfEngagementPDF', {
        engagementInfo,
        content: terms,
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      console.error('Error exporting PDF:', error);
      alert('Failed to export PDF. Please try again.');
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="min-h-screen bg-slate-50 p-6"
    >
      <div className="max-w-5xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-slate-900">Terms of Engagement</h1>
            <p className="text-slate-500 mt-1">Business Annex Platform</p>
          </div>
          <div className="text-right">
            <p className="text-sm text-slate-500">Last saved: {lastSaved.toLocaleTimeString()}</p>
            <Button
              onClick={generateTerms}
              disabled={isGenerating}
              className="bg-violet-600 hover:bg-violet-700 text-white mt-3"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <RefreshCw className="w-4 h-4 mr-2" />
                  Generate Terms
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Legal Disclaimer */}
        <div className="flex gap-3 p-4 bg-amber-50 border border-amber-200 rounded-lg">
          <AlertCircle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div className="text-sm text-amber-800">
            <strong>Legal Disclaimer:</strong> This Terms of Engagement document is generated by AI and should be reviewed by a qualified legal professional before use. Business Annex provides this template as a guideline only and does not constitute legal advice.
          </div>
        </div>

        {/* Engagement Information Form */}
        <EngagementInfoForm engagementInfo={engagementInfo} setEngagementInfo={setEngagementInfo} />

        {/* Terms Document */}
        {terms ? (
          <>
            <DocumentContent
              content={terms}
              title="Terms of Engagement"
              infoData={engagementInfo}
              infoDisplayFields={[
                { key: 'clientName', label: 'Client' },
                { key: 'engagementType', label: 'Type' },
                { key: 'date', label: 'Start Date' }
              ]}
              onUpdate={setTerms}
              onExport={exportPDF}
              onRegenerate={generateTerms}
              isGenerating={isGenerating}
            />
            {versions.length > 0 && (
              <DocumentVersionHistory versions={versions} onRestore={(v) => restoreVersion(v, engagementInfo)} />
            )}
          </>
        ) : (
          <Card className="border-0 shadow-lg p-12 text-center">
            <p className="text-slate-500 mb-4">No Terms of Engagement generated yet.</p>
            <Button
              onClick={generateTerms}
              disabled={isGenerating}
              className="bg-violet-600 hover:bg-violet-700 text-white mx-auto"
            >
              {isGenerating ? 'Generating...' : 'Generate Terms'}
            </Button>
          </Card>
        )}
      </div>
    </motion.div>
  );
}