import React, { useState, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { AlertCircle, Download, RefreshCw, Loader2 } from 'lucide-react';
import { motion } from 'framer-motion';

import EngagementInfoForm from '@/components/TermsOfEngagement/EngagementInfoForm';
import TermsOfEngagementContent from '@/components/TermsOfEngagement/TermsOfEngagementContent';
import EngagementVersionHistory from '@/components/TermsOfEngagement/EngagementVersionHistory';

export default function TermsOfEngagement() {
  const [engagementInfo, setEngagementInfo] = useState({
    clientName: '',
    engagementType: 'consulting',
    scope: '',
    fees: '',
    date: new Date().toISOString().split('T')[0]
  });
  const [terms, setTerms] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [lastSaved, setLastSaved] = useState(new Date());
  const [versions, setVersions] = useState([]);

  // Auto-save every 60 seconds
  useEffect(() => {
    const autoSaveTimer = setInterval(() => {
      if (terms) {
        saveTerms();
      }
    }, 60000);
    return () => clearInterval(autoSaveTimer);
  }, [terms, engagementInfo]);

  const saveTerms = async () => {
    try {
      setLastSaved(new Date());
      await base44.functions.invoke('saveTermsOfEngagement', {
        engagementInfo,
        terms,
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      console.error('Error saving terms:', error);
    }
  };

  const generateTerms = async () => {
    if (!engagementInfo.clientName) {
      alert('Please enter client name first');
      return;
    }

    setIsGenerating(true);
    try {
      const result = await base44.functions.invoke('generateTermsOfEngagement', {
        engagementInfo,
        platformName: 'Business Annex'
      });

      setTerms(result);
      setVersions([
        ...versions,
        {
          id: Date.now(),
          timestamp: new Date().toISOString(),
          terms: result,
          note: 'AI Generated'
        }
      ]);
      saveTerms();
    } catch (error) {
      console.error('Error generating terms:', error);
      alert('Failed to generate terms. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleTermsUpdate = (updatedContent) => {
    setTerms(updatedContent);
  };

  const exportPDF = async () => {
    try {
      await base44.functions.invoke('exportTermsOfEngagementPDF', {
        engagementInfo,
        content: terms,
        timestamp: new Date().toISOString()
      });
    } catch (error) {
      console.error('Error exporting PDF:', error);
      alert('Failed to export PDF. Please try again.');
    }
  };

  const restoreVersion = (version) => {
    setTerms(version.terms);
    setVersions([
      ...versions,
      {
        id: Date.now(),
        timestamp: new Date().toISOString(),
        terms: version.terms,
        note: `Restored from ${new Date(version.timestamp).toLocaleString()}`
      }
    ]);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="min-h-screen bg-slate-50 p-6"
    >
      <div className="max-w-5xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-slate-900">Terms of Engagement</h1>
            <p className="text-slate-500 mt-1">Business Annex Platform</p>
          </div>
          <div className="text-right">
            <p className="text-sm text-slate-500">Last saved: {lastSaved.toLocaleTimeString()}</p>
            <div className="flex gap-2 mt-3">
              <Button
                onClick={generateTerms}
                disabled={isGenerating}
                className="bg-violet-600 hover:bg-violet-700 text-white"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <RefreshCw className="w-4 h-4 mr-2" />
                    Generate Terms
                  </>
                )}
              </Button>
              <Button
                onClick={saveTerms}
                variant="outline"
                className="border-slate-300"
              >
                Save Now
              </Button>
            </div>
          </div>
        </div>

        {/* Legal Disclaimer */}
        <div className="flex gap-3 p-4 bg-amber-50 border border-amber-200 rounded-lg">
          <AlertCircle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div className="text-sm text-amber-800">
            <strong>Legal Disclaimer:</strong> This Terms of Engagement document is generated by AI and should be reviewed by a qualified legal professional before use. Business Annex provides this template as a guideline only and does not constitute legal advice.
          </div>
        </div>

        {/* Engagement Information Form */}
        <EngagementInfoForm engagementInfo={engagementInfo} setEngagementInfo={setEngagementInfo} />

        {/* Terms Document */}
        {terms ? (
          <TermsOfEngagementContent
            content={terms}
            engagementInfo={engagementInfo}
            onUpdate={handleTermsUpdate}
            onExport={exportPDF}
            onRegenerate={generateTerms}
            isGenerating={isGenerating}
          />
        ) : (
          <Card className="border-0 shadow-lg p-12 text-center">
            <p className="text-slate-500 mb-4">No Terms of Engagement generated yet.</p>
            <Button
              onClick={generateTerms}
              disabled={isGenerating}
              className="bg-violet-600 hover:bg-violet-700 text-white mx-auto"
            >
              {isGenerating ? 'Generating...' : 'Generate Terms'}
            </Button>
          </Card>
        )}

        {/* Version History */}
        {versions.length > 0 && (
          <EngagementVersionHistory versions={versions} onRestore={restoreVersion} />
        )}
      </div>
    </motion.div>
  );
}